### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by JamRemco** [Splitwirez/Mechanism-for-Avalonia#3]
Hello world

I did download the repo but i can not build it

![image](https://user-images.githubusercontent.com/58340108/82725912-b9adbd80-9ce0-11ea-8023-c99af50a70f3.png)

did you use an unoffical build?

Regards,

Remco

**Comment by Splitwirez** [comment]
Oh shoot, so sorry I forgot to respond to this the other day. I've been using the nightly builds of Avalonia for the time being. You can find instructions to get at those here: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

...that reminds me, I'll need to incorporate the package source into the repo at some point. Woops.

**Comment by JamRemco** [comment]
> Oh shoot, so sorry I forgot to respond to this the other day.
> 
No problemo.

Now i am late with responding.  bussy on avalonia

**Comment by Splitwirez** [comment]
For anyone reading this, Mechanism is now back on the main Avalonia NuGet feed thing, presently using Avalonia 0.10.0 Release Candidate 1. As such, this should no longer be an issue. If it is though, please open a new issue post as necessary.
