### ISSUE TITLE
AvaloniaRibbon

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/Mechanism-for-Avalonia#4]
Hello, your project has not been submitted. Are you going to continue to maintain it?

**Comment by Splitwirez** [comment]
If you're referring to AvaloniaRibbon, then yes, I do plan to continue maintaining it...but given amazerol's (the AvaloniaRibbon project founder's) absence, I may end up branching off in my own direction, rather than trying to continue contributing upstream.

**Comment by jinyuttt** [comment]
ok,thanks.
