### ISSUE TITLE
HI,Ask some questions

### ISSUE THREAD

**Issue by wuzlai** [Splitwirez/Mechanism-for-Avalonia#5]
Hi,Excuse you.i find you have use cefnet.avalonia.now i also use it .now i have some peoblems. 
I  want to get the content of the page in the browser. But I don't know how to deal with it. Also, I also want to know if there is a page rendering loading event. I need to do some extra processing after the page is loaded. Do you know the answers to these questions? Or do you have any better suggestions. I need a webview control and rich text editor. @Splitwirez  @Splitwirez

**Comment by Splitwirez** [comment]
I'm not familiar with CefNet.Avalonia. I've been working on updating this though: https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/pull/7

**Comment by wuzlai** [comment]
> I'm not familiar with CefNet.Avalonia. I've been working on updating this though: [AvaloniaUI/Avalonia.HtmlRenderer#7](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/pull/7)

Hi，man,may be your Avalonia.HtmlRenderer can be my best choice. i download the Avalonia.HtmlRenderer,but do not konw how to use it. can you provide me some demo for using Avalonia.HtmlRenderer.thank you.

**Comment by Splitwirez** [comment]
I just realized I...completely forgot about this issue until now. I am so sorry about that.

If you're still looking, my changes can be seen here: https://github.com/Splitwirez/Avalonia.HtmlRenderer

If memory serves, there's a a sample app in there, too.

**Comment by wuzlai** [comment]
> I just realized I...completely forgot about this issue until now. I am so sorry about that.
> 
> If you're still looking, my changes can be seen here: https://github.com/Splitwirez/Avalonia.HtmlRenderer
> 
> If memory serves, there's a a sample app in there, too.

nothing. Thank you for your reply. I will study the information you provided later. Thank you
