### ISSUE TITLE
Question related to controls

### ISSUE THREAD

**Issue by Junaid-Amjad** [Splitwirez/Mechanism-for-Avalonia#6]
Hi, i have run the code but i want to use the controls in my application. How can i achieve it? i tried to add `Mechanism.AvaloniaUI` and `Mechanism.AvaloniaUI.Sample` solution in my project and copy pasted the MainWindow.xaml from `Mechanism.AvaloniaUI.Sample` into my project but the output was not clean
![GUI](https://user-images.githubusercontent.com/75033105/104741576-39563400-576b-11eb-815f-e346707f1655.png). Thanks in advance.

**Comment by Splitwirez** [comment]
Have you added the Mechanism styles to your `App.xaml`/`App.axaml`?

**Comment by Junaid-Amjad** [comment]
It works. thanks for the quick response.

**Comment by Splitwirez** [comment]
> It works. thanks for the quick response.

Not a problem, glad to hear it's working now.
